### ISSUE TITLE
Hardcoded addresses only for Mumbai network

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader_filecoin#27]
In `dbs_filecoin/src/config/contractInfo.js` there are hardcoded addresses only for Mumbai network. We will need to update this before it will work on other networks.

```javascript
import dotenv from 'dotenv';

dotenv.config();

export default {
  80001: {
    currency: {
      USDT: '0x742DfA5Aa70a8212857966D491D67B09Ce7D6ec7',
      USDC: '0x21C561e551638401b937b03fE5a0a0652B99B7DD',
      TUSD: '0x9aa7fEc87CA69695Dd1f879567CcF49F3ba417E2',
    },
    rpc: process.env.MUMBAI_RPC,
    contract: '0x0ff9092e55d9f6CCB0DD4C490754811bc0839866',
  },
};

```

**Comment by jamiehewitt15** [comment]
@xlassix @ravish1729 @nandit123 Are you able to provide some more information about the deposit contract? Is there some documentation? Do you know what networks it has been deployed to?

**Comment by jamiehewitt15** [comment]
@xlassix @ravish1729 @nandit123 Can you provide more information about the deposit contract? We will need the addresses for the other networks where it is deployed.

**Comment by jamiehewitt15** [comment]
@ravish1729 mentioned to me on Telegram that the deposit contract is only deployed on Mumbai

**Comment by AnaLoznianu** [comment]
I assume we can unblock this as the contracts are deployed. @alexcos20 or @jamiehewitt15 can you confirm?

**Comment by xlassix** [comment]
Yes, this was resolved on PR 16. all addresses can be configured through environment variables now. 
kindly see the updated readme for more
